/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import accesoADatos.SocioData;
import entidades.Socio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Martin
 */
public class vistaSocio extends javax.swing.JInternalFrame {
    private int TipoRadio=0;
    private String buscar="";
    private  DefaultTableModel modeloTable;
    private ArrayList<Socio> listaSocio=new ArrayList<Socio>();
    private SocioData socioData;
    /**
     * Creates new form vistaSocio
     */
    public vistaSocio() {
        initComponents();
        socioData=new SocioData();
        armarEncabezado();
        textModificado();
        disableButtonInicio();
        enlazarListenerRadio();
        TipoRadio=Filtro();
        
        jTxtBuscar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrup = new javax.swing.ButtonGroup();
        jtbpContenedor = new javax.swing.JTabbedPane();
        jPnlSocios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblDatos = new javax.swing.JTable();
        jTxtBuscar = new javax.swing.JTextField();
        jRbCodigo = new javax.swing.JRadioButton();
        jRbNombreApellido = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRbTodos = new javax.swing.JRadioButton();
        jRbDni = new javax.swing.JRadioButton();
        jCbBaja = new javax.swing.JCheckBox();
        jPnlEdicion = new javax.swing.JPanel();
        jTxtDni = new javax.swing.JTextField();
        jTxtEdad = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtCorreo = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnNuevo = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jCbActivo = new javax.swing.JCheckBox();
        jlbliDsocio = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de socios");

        jtbpContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbpContenedorMouseClicked(evt);
            }
        });

        jPnlSocios.setBackground(new java.awt.Color(51, 153, 255));

        jTblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblDatos);

        jTxtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGrup.add(jRbCodigo);
        jRbCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jRbCodigo.setText("Codigo");

        btnGrup.add(jRbNombreApellido);
        jRbNombreApellido.setForeground(new java.awt.Color(255, 255, 255));
        jRbNombreApellido.setText("Nombre y apellido");

        jButton1.setText("Buscar");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("# Seleccione  la fila para gestionar al socio");

        btnGrup.add(jRbTodos);
        jRbTodos.setForeground(new java.awt.Color(255, 255, 255));
        jRbTodos.setText("Todos");

        btnGrup.add(jRbDni);
        jRbDni.setForeground(new java.awt.Color(255, 255, 255));
        jRbDni.setText("Dni");

        jCbBaja.setBackground(new java.awt.Color(255, 102, 102));
        jCbBaja.setForeground(new java.awt.Color(255, 255, 255));
        jCbBaja.setText("Baja");
        jCbBaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));

        javax.swing.GroupLayout jPnlSociosLayout = new javax.swing.GroupLayout(jPnlSocios);
        jPnlSocios.setLayout(jPnlSociosLayout);
        jPnlSociosLayout.setHorizontalGroup(
            jPnlSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSociosLayout.createSequentialGroup()
                .addGroup(jPnlSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlSociosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPnlSociosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnlSociosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPnlSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlSociosLayout.createSequentialGroup()
                                .addComponent(jRbTodos)
                                .addGap(18, 18, 18)
                                .addComponent(jRbDni)
                                .addGap(18, 18, 18)
                                .addComponent(jRbCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jRbNombreApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jCbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtBuscar))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnlSociosLayout.setVerticalGroup(
            jPnlSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlSociosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPnlSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlSociosLayout.createSequentialGroup()
                        .addGroup(jPnlSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbCodigo)
                            .addComponent(jRbNombreApellido)
                            .addComponent(jRbTodos)
                            .addComponent(jRbDni)
                            .addComponent(jCbBaja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jtbpContenedor.addTab("Busqueda", jPnlSocios);

        jPnlEdicion.setBackground(new java.awt.Color(51, 153, 255));

        jTxtDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtDni.setNextFocusableComponent(jTxtNombre);

        jTxtEdad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtEdad.setNextFocusableComponent(jTxtCorreo);

        jTxtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNombre.setNextFocusableComponent(jTxtApellido);

        jTxtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtCorreo.setNextFocusableComponent(jTxtTelefono);

        jTxtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtTelefono.setNextFocusableComponent(jCbActivo);

        jTxtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtApellido.setNextFocusableComponent(jTxtEdad);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion de socios");

        jBtnNuevo.setText("Nuevo");

        jBtnGuardar.setText("Guardar");

        jBtnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");

        jCbActivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCbActivo.setForeground(new java.awt.Color(255, 255, 255));
        jCbActivo.setSelected(true);
        jCbActivo.setText("Activo");

        jlbliDsocio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbliDsocio.setForeground(new java.awt.Color(255, 255, 255));
        jlbliDsocio.setText(" # ");

        javax.swing.GroupLayout jPnlEdicionLayout = new javax.swing.GroupLayout(jPnlEdicion);
        jPnlEdicion.setLayout(jPnlEdicionLayout);
        jPnlEdicionLayout.setHorizontalGroup(
            jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEdicionLayout.createSequentialGroup()
                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlEdicionLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel2))
                    .addGroup(jPnlEdicionLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbActivo)
                            .addGroup(jPnlEdicionLayout.createSequentialGroup()
                                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPnlEdicionLayout.createSequentialGroup()
                                        .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTxtApellido)
                                    .addComponent(jTxtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxtDni, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(73, 73, 73)
                                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPnlEdicionLayout.createSequentialGroup()
                                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlbliDsocio))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPnlEdicionLayout.setVerticalGroup(
            jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEdicionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jlbliDsocio)
                .addGap(31, 31, 31)
                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jCbActivo)
                .addGap(79, 79, 79)
                .addGroup(jPnlEdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jBtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(143, 143, 143))
        );

        jtbpContenedor.addTab("Gestion", jPnlEdicion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbpContenedor)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbpContenedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbpContenedorMouseClicked
        //jTxtBuscar.requestFocusInWindow();
       // jPnlSocios.getV
                int selectedIndex = jtbpContenedor.getSelectedIndex();
                
                if(selectedIndex==0){
                    System.out.println(selectedIndex);
                    //jTxtDni.requestFocusInWindow();
                    jTxtBuscar.requestFocus();
                }else{
                     jTxtDni.requestFocus();
                    
                }
    }//GEN-LAST:event_jtbpContenedorMouseClicked

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrup;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCbActivo;
    private javax.swing.JCheckBox jCbBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlEdicion;
    private javax.swing.JPanel jPnlSocios;
    private javax.swing.JRadioButton jRbCodigo;
    private javax.swing.JRadioButton jRbDni;
    private javax.swing.JRadioButton jRbNombreApellido;
    private javax.swing.JRadioButton jRbTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblDatos;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtBuscar;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtDni;
    private javax.swing.JTextField jTxtEdad;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTelefono;
    private javax.swing.JLabel jlbliDsocio;
    private javax.swing.JTabbedPane jtbpContenedor;
    // End of variables declaration//GEN-END:variables

    private void textModificado(){
        libs.FuncionesComunes.textPrompt(jTxtDni,"D.N.I (numerico)");
        libs.FuncionesComunes.textPrompt(jTxtNombre,"Nombre");
        libs.FuncionesComunes.textPrompt(jTxtApellido,"Apellido");
        libs.FuncionesComunes.textPrompt(jTxtCorreo,"Correo (name@dominio.com)");
        libs.FuncionesComunes.textPrompt(jTxtTelefono,"Telefono (numerico)");
        libs.FuncionesComunes.textPrompt(jTxtEdad,"Edad (numerico)");
        
        
    }
    
    private void disableButtonInicio(){
        jBtnEliminar.setEnabled(false);
        jBtnNuevo.setEnabled(false);
    }
    
    private void disableButtonEditar(){
        jBtnEliminar.setEnabled(true);
        jBtnNuevo.setEnabled(true);
    }
    
    private void listar(){
        if(validarBuscar()){
            
            
        }
    }
    
    private void listarTodos(){
        if(validarBuscar()){
            listaSocio=socioData.listarSocio(CheckBaja());
           
            if(listaSocio.size()>0){
                libs.FuncionesComunes.eliminarFilas(jTblDatos);
                for (Socio socio : listaSocio) {
                    modeloTable.addRow(new Object[]{
                        socio.getIdSocio(),
                        socio.getDni(),
                        socio.getNombre(),
                        socio.getApellido(),
                        socio.getEdad(),
                        socio.getTelefono()
                    });
                }
            }
            
        }
    }
    
    private boolean validarBuscar(){
        boolean res=false;
        buscar=jTxtBuscar.getText().trim();
        
        if(TipoRadio!=0 && !buscar.isEmpty()){
            
            if(TipoRadio==2 || TipoRadio==3){
               if(libs.FuncionesComunes.validarNumericos(buscar)){
                   res=true;
               }
               else{
                   libs.FuncionesComunes.vistaDialogo("Para codigo o Dni los campos son numericos.", 0);
               }
            }
            else{
                if(TipoRadio==4 || TipoRadio==1){
                    res=true;
                }
            }
        }else{
            if(TipoRadio==1){
                res=true;
            }
        }
        
        return res;
    }
    
    
    private  int Filtro(){
        int radio=1;
        ButtonModel selectedModel = btnGrup.getSelection();
        
        if (selectedModel != null) {
            libs.FuncionesComunes.eliminarFilas(jTblDatos);
            jTxtBuscar.requestFocus();
            libs.FuncionesComunes.textPrompt(jTxtBuscar, " ");
                     if (selectedModel == jRbDni.getModel()) {
                         libs.FuncionesComunes.textPrompt(jTxtBuscar, "D.N.I - 34877112");
                        radio=2;
                    } else if (selectedModel == jRbCodigo.getModel()) {
                         libs.FuncionesComunes.textPrompt(jTxtBuscar, "Codigo - 100");
                         radio=3;
                    }
                     else if (selectedModel == jRbNombreApellido.getModel()) {
                       libs.FuncionesComunes.textPrompt(jTxtBuscar, "Nombre o Apellido");  
                       radio=4;
                    }
                     
        } else{
            radio=1;
        }   
    
        return  radio;
    }
         //
        
         private void enlazarListenerRadio(){
             jRbTodos.addActionListener(radioButtonListener);
             jRbDni.addActionListener(radioButtonListener);
             jRbCodigo.addActionListener(radioButtonListener);
             jRbNombreApellido.addActionListener(radioButtonListener);
         }
    
        ActionListener radioButtonListener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               TipoRadio=Filtro();
               
               if(TipoRadio==1){
                   listarTodos();
               }
            }
        };
        
        
        
    private void armarEncabezado() {
        modeloTable = libs.FuncionesComunes.ArmadoEncabezados(entidades.Socio.CabeceraSocio.Codigo);
        jTblDatos.setModel(modeloTable);
        //libs.FuncionesComunes.alinearCabeceras(1, "right", jTblDatos);

    }
        
    private int CheckBaja(){
        int res;
        if(jCbBaja.isSelected()){
            res=0;
        }else{
            res=1;
        }
      
         return res;
    }
    
    
   
}
